name: Zip it up
on:
  push:
jobs:
  build-lnx:
    name: Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Install dependencies
      run: | 
        # swy: absolutely braindead breakage: https://github.com/actions/runner-images/issues/4589#issuecomment-1260157764
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
        sudo apt-get update -qq
        sudo apt-get remove -qq libmono* moby* mono* nginx* php* libgdiplus libpcre2-posix3 libzip4

        sudo apt-get update
        sudo apt-get upgrade    

        sudo dpkg --add-architecture i386
        
        sudo apt-get update
        sudo apt-get upgrade
        
        sudo apt install wine32  -yy --force-yes

        sudo apt install --install-recommends xvfb tree flip curl unzip lsof jq -yy --force-yes
        sudo apt install p7zip

    - name: Pack things up
      id: pack
      run: |
        git fetch --unshallow || git fetch --all
        # swy: find the previous run from the same type that is not us
        prev_run_shas="`curl -s --location --fail 'https://api.github.com/repos/swyter/mab-tools/actions/runs' | jq -r '.workflow_runs[] | select(.name | test("Zip it up")) | select(.id != '$GITHUB_RUN_ID') | .head_sha'`"
        echo -ne "[i] previous run revisions:\n$prev_run_shas\n\n"
        prev_run_sha="`echo "$prev_run_shas" | head -n1`"
        echo "prev=$prev_run_sha cur=`git rev-parse --short HEAD`"
    
        # swy: only pack it when the folder has changed since the last time we ran a GitHub Actions job or there's a !force keyword in the last commit message
        if [[ ! -z "$(git diff --quiet HEAD "$prev_run_sha" -- mab_sco_*.py mab_sco_drag_and_drop_here.cmd || echo changed)" || "$(git rev-list --format=%B --max-count=1 HEAD | grep --count --ignore-case --max-count=1 '!force')" -ge 1 ]]; then
          # swy: add a dummy screen for Wine to proceed headless, dial down the Wine log spam
          #      we need Wine to run the Windows version of PyInstaller to turn the .py into a self-contained .exe
          Xvfb :1 -screen 0 800x600x16 &
          export DISPLAY=:1
          export WINEDLLOVERRIDES="mscoree,mshtml="
          export WINEDEBUG=fixme-all
          
          WINEARCH=win32 wineboot -u

          # swy: newer versions of Python don't really seem to install properly under Wine; we could also use the embedded version and install pip on top by removing the python310._pth file from the extracted .zip first
          curl -LO https://www.python.org/ftp/python/3.8.9/python-3.8.9.exe
          wine python-3.8.9.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Include_launcher=0 Include_tcltk=0
          
          wine pip install nuitka --no-python-version-warning --disable-pip-version-check # swy: investigate potentially building or downloading orderedset with msys2, the compiler complains about not using it, for speed

          cur_date_ver_tiny="$(date +%Y.%m.%d -u)"
          cur_date_ver_long="$(date +%Y.%m.%d-%H.%M -u)"

          # swy: compile the individual Python 3 binaries as native code with Nuitka, leaving only the shared python38.dll behind
          wine python -m nuitka mab_sco_unpack.py           --assume-yes-for-downloads --mingw64 --lto=yes --show-anti-bloat-changes --standalone --remove-output --show-modules --follow-imports --follow-stdlib --windows-file-description="Mount&Blade SceneObj Tools" --company-name='Created by Swyter' --product-version="${cur_date_ver_tiny}" --force-dll-dependency-cache-update
          wine python -m nuitka mab_sco_unpacked_reindex.py --assume-yes-for-downloads --mingw64 --lto=yes --show-anti-bloat-changes --standalone --remove-output --show-modules --follow-imports --follow-stdlib --windows-file-description="Mount&Blade SceneObj Tools" --company-name='Created by Swyter' --product-version="${cur_date_ver_tiny}" --force-dll-dependency-cache-update
          wine python -m nuitka mab_sco_repack.py           --assume-yes-for-downloads --mingw64 --lto=yes --show-anti-bloat-changes --standalone --remove-output --show-modules --follow-imports --follow-stdlib --windows-file-description="Mount&Blade SceneObj Tools" --company-name='Created by Swyter' --product-version="${cur_date_ver_tiny}" --force-dll-dependency-cache-update

          # swy: each binary has its own folder with full DLL dependencies, move them to a common one called «dist» to follow the PyInstaller folder scheme
          mkdir dist && cp -r mab_sco_unpack.dist/* dist
          cp mab_sco_unpacked_reindex.dist/mab_sco_unpacked_reindex.exe dist
          cp mab_sco_repack.dist/mab_sco_repack.exe                     dist

          pushd dist && rm api-*.dll ucrt*.dll *.pyd vcruntime*.dll || true

          # swy: PyInstaller drops the final .exe in a ./dist subfolder, go inside, zip them and go back
          7z -mm=Deflate -mfb=258 -mpass=15 a "../swy-sco-tools-${cur_date_ver_long}.zip" mab_sco_*.exe *.dll ../mab_sco_drag_and_drop_here.cmd
          popd
        else
          echo "[no changes in the add-on folder this time around; skipped]"
        fi

    - name: Upload Release Asset
      id: upload-release-asset
      run: |
        owner="swyter"; repo="mab-tools"; release_id="78295290"
        
        FILENAME="$(basename "$(find . -name '*tools*.zip' | sort -r -u | head -n 1)")"
        GH_ASSET="https://uploads.github.com/repos/$owner/$repo/releases/$release_id/assets?name=$FILENAME"
        echo "$GH_ASSET"; echo "$FILENAME"
        
        if [[ -f "$FILENAME" ]]; then
          curl --fail --location --data-binary @"$FILENAME" -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' -H "Content-Type: application/octet-stream" "$GH_ASSET"
        else
          echo "[no changes in the add-on folder this time around; skipped]"
        fi
